//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int MessageID { get; set; }
        public Nullable<int> YeuCauID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual YeuCau YeuCau { get; set; }
        public virtual User User { get; set; }
    }
}
